[[redirects]]
from = "/login"
to = "/login"
status = 200

[[redirects]]
from = "/register"
to = "/register"
status = 200

[[redirects]]
from = "/authors"
to = "/authors"
status = 200

[[redirects]]
from = "/"
to = "/"
status = 200